# Generated by Django 2.2 on 2020-08-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200824_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('country', 'Страна'), ('Belarus', 'Беларусь'), ('Brazil', 'Бразилия'), ('United Kingdom', 'Великобритания'), ('Russia', 'Россия'), ('Kyrgyzstan', 'Киргизия')], default='country', max_length=20, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('gender', 'Пол'), ('girl', 'Мужской'), ('men', 'Женский')], default='gender', max_length=20, verbose_name='Пол'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
