# Generated by Django 2.2 on 2020-08-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('gender', 'Пол'), ('men', 'Мужской'), ('girl', 'Женский')], default='gender', max_length=20, verbose_name='Пол'),
        ),
    ]
